

services:
  postgres:
    image: postgres:latest
    container_name: test_db
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env


volumes:
  postgres_data:
