# Generated by Django 4.2.6 on 2023-10-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('place_code', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('plane_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plane_value')),
            ],
        ),
    ]
