# Generated by Django 4.2.6 on 2024-01-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('place_code', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
