from django.urls import path

from apps.amadeus_api.api.views import (
    AirportDirectView,
    CheapestFlightsView,
    CheapestJourneyView,
    CheckinLinksView,
    DetailsAirportView,
    FavorableFlightsDatesView,
    ListCityHotelsView,
    ListNearAirportsView,
    PercentageOnTimeDeparturesView,
    PredictFlightDelayView,
    PredictTravelChoiceView,
    PredictTravelPurposeView,
    RecommendedLocationsView,
)

urlpatterns = [
    path('amadeus/cheapest_flights/<str:city_code>', CheapestFlightsView.as_view(), name='cheapest_flights'),
    path('amadeus/favorable_flights_dates/<str:city_code_from>/<str:city_code_to>',
         FavorableFlightsDatesView.as_view(), name='favorable_flights_dates'),
    path('amadeus/cheapest_journey/<str:city_code_from>/<str:city_code_to>/<str:date>/<str:adults_count>',
         CheapestJourneyView.as_view(), name='cheapest_journey'),
    path('amedeus/predict_travel_choice/<str:city_code_from>/<str:city_code_to>/<str:date>/<str:adults_count>',
         PredictTravelChoiceView.as_view(), name='predict_travel_choice'),
    path('amadeus/predict_travel_purpose/<str:city_code_from>/<str:city_code_to>/<str:departure_date>/<str:arrival_date>/<str:search_date>',
         PredictTravelPurposeView.as_view(), name='predict_travel_purpose'),
    path('amadeus/predict_flight_delay/<str:city_code_from>/<str:city_code_to>/<str:departure_date>/<str:departure_time>/<str:arrival_date>/<str:arrival_time>/<str:aircraft_code>/<str:carrier_code>/<str:flight_number>/<str:duration>',
         PredictFlightDelayView.as_view(), name='predict_flight_delay'),
    path('amadeus/details_airport/<str:airport_code>', DetailsAirportView.as_view(), name='details_airport'),
    path('amadeus/list_near_airports/<str:longitude>/<str:latitude>',
         ListNearAirportsView.as_view(), name='list_near_airports'),
    path('amadeus/checkin_links/<str:airline_code>/<str:language>', CheckinLinksView.as_view(), name='checkin_links'),
    path('amadeus/recommended_locations/<str:city_code>/<str:country_code>',
         RecommendedLocationsView.as_view(), name='recommended_locations'),
    path('amadeus/percentage_ofontime_departures/<str:airport_code>/<str:date>',
         PercentageOnTimeDeparturesView.as_view(), name='percentage_ofontime_departures'),
    path('amadeus/airport_direct/<str:airport_code>', AirportDirectView.as_view(), name='airport_direct'),
    path('amadeus/list_city_hotels/<str:city_code>', ListCityHotelsView.as_view(), name='list_city_hotels'),
]
